import = [ "~/.config/alacritty/themes/active.toml" ]
live_config_reload = true
working_directory = "None"

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
# ref_test = false
render_timer = false

[font]
# AppleFontSmoothing = true
size = 18.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "JetBrains Mono"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 4
y = 4
